repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.0
    hooks:
    -   id: ruff
        args: [ --fix ]
-   repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.10.0
    hooks:
    -   id: black
-   repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.385
    hooks:
    -   id: pyright
        name: pyright (3.8)
        args: [--pythonversion=3.8]
        files: \.pyi?$
    -   id: pyright
        name: pyright (3.9)
        args: [--pythonversion=3.9]
        files: \.pyi?$
    -   id: pyright
        name: pyright (3.10)
        args: [--pythonversion=3.10]
        files: \.pyi?$
    -   id: pyright
        name: pyright (3.11)
        args: [--pythonversion=3.11]
        files: \.pyi?$
